### ISSUE TITLE
Bug: crash in device=cuda mode

### ISSUE THREAD

**Issue by Nomad1** [iffyloop/TripoSR-Bake#2]
There is a minor bug when non-CPU device is used for torch:
```(2/3): Sample NeRF to uniform grid
(3/3): Marching cubes
Traceback (most recent call last):
  File "/home/gorbuz/content/TripoSR-Bake/01-mesh.py", line 202, in <module>
    main()
  File "/home/gorbuz/content/TripoSR-Bake/01-mesh.py", line 192, in main
    mesh_result = run_mesh(args, tsr_result, grid_result)
  File "/home/gorbuz/content/TripoSR-Bake/01-mesh.py", line 91, in run_mesh
    .numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```
It's easily fixed by adding .cpu() to line 91 of [01-mesh.py](../blob/master/01-mesh.py). It's simple enough to fix so I won't submit a PR for it.

**Comment by iffyloop** [comment]
Perfect, thanks for reporting! Should be fixed now.
