### ISSUE TITLE
Exception:(standalone) XOpenDisplay: cannot open display

### ISSUE THREAD

**Issue by 55renchen** [iffyloop/TripoSR-Bake#6]
Hello, when i run python 02-texture.py,i meet the problem "Exception:(standalone) XOpenDisplay: cannot open display".
How can i solve this issue?
Hope to your reply!

**Comment by 55renchen** [comment]
The output is :

(1/5): Load TripoSR and scene codes
(2/5): Load mesh
(3/5): Generate UVs
(4/5): Rasterize UV atlas
Traceback (most recent call last):
  File "/mnt/workspace/TripoSR-Bake/02-texture.py", line 268, in <module>
    main()
  File "/mnt/workspace/TripoSR-Bake/02-texture.py", line 245, in main
    rasterize_result = run_rasterize(args, mesh_result, xatlas_result)
  File "/mnt/workspace/TripoSR-Bake/02-texture.py", line 53, in run_rasterize
    ctx = moderngl.create_context(standalone=True)
  File "/mnt/workspace/TripoSR-Bake/venv/lib/python3.10/site-packages/moderngl/__init__.py", line 1936, in create_context
    ctx.mglo, ctx.version_code = mgl.create_context(glversion=require, mode=mode, **settings)
  File "/mnt/workspace/TripoSR-Bake/venv/lib/python3.10/site-packages/glcontext/__init__.py", line 90, in create
    return x11.create_context(**kwargs)
Exception: (standalone) XOpenDisplay: cannot open display

**Comment by iffyloop** [comment]
See #1
